### ISSUE TITLE
Adding Register Vec initialisation

### ISSUE THREAD

**Issue by Martoni** [freechipsproject/chisel-cheatsheet#1]
[a copy from chisel repository [issue](https://github.com/freechipsproject/chisel3/issues/1105)]

**Type of issue**: documentation

**Impact**: no functional change

**Development Phase**: request

**Other information**
Is it possible to add Vec initialization ? 

For example, here a vec initialization of a register file of 31 UInt registers of 32bits width.

` val regfile = RegInit(VecInit(Seq.fill(31)(0.U(32.W))))`

**Comment by chick** [comment]
This will be in the next release
